# Generated by Django 6.0 on 2025-12-30 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_categorymodel_id_alter_productmodel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='star',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.productmodel'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='text',
            field=models.TextField(),
        ),
    ]
